name: visualizer
description: "Collection of visualizers made by me!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  gap: ^3.0.1
  provider: ^6.1.1
  toggle_switch: ^2.1.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/