name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main  # Set your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      
    - name: Replace Firebase Config in index.html
      run: |
        sed -i 's/%%API_KEY%%/${{ secrets.API_KEY }}/g' build/web/index.html
        sed -i 's/%%AUTH_DOMAIN%%/${{ secrets.AUTH_DOMAIN }}/g' build/web/index.html
        sed -i 's/%%PROJECT_ID%%/${{ secrets.PROJECT_ID }}/g' build/web/index.html
        sed -i 's/%%STORAGE_BUCKET%%/${{ secrets.STORAGE_BUCKET }}/g' build/web/index.html
        sed -i 's/%%MESSAGING_SENDER_ID%%/${{ secrets.MESSAGING_SENDER_ID }}/g' build/web/index.html
        sed -i 's/%%APP_ID%%/${{ secrets.APP_ID }}/g' build/web/index.html
        sed -i 's/%%MEASUREMENT_ID%%/${{ secrets.MEASUREMENT_ID }}/g' build/web/index.html
    
    - name: Build
      run: flutter build web  # Build your Flutter web app

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
